# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#do fib seq
num1 = 1
num2 = 2


evensBelow4Mil = [2]

while num2 < 4000000:
	oldNum2 = num2
	num2 = num2 + num1
	num1 = oldNum2
	
	if num2 <= 4000000:
		if num2 % 2 == 0:
			evensBelow4Mil.append(num2)
	
print(sum(evensBelow4Mil))



